twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        parameters:
            # Custom parameters
            project_name: '%app.project_name%'
